#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz2.models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoruBankası")]
	public partial class SoruBankasıDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKategori(Kategori instance);
    partial void UpdateKategori(Kategori instance);
    partial void DeleteKategori(Kategori instance);
    partial void InsertSeviye(Seviye instance);
    partial void UpdateSeviye(Seviye instance);
    partial void DeleteSeviye(Seviye instance);
    partial void InsertKlasikSoru(KlasikSoru instance);
    partial void UpdateKlasikSoru(KlasikSoru instance);
    partial void DeleteKlasikSoru(KlasikSoru instance);
    partial void InsertCoktanSecmeliSoru(CoktanSecmeliSoru instance);
    partial void UpdateCoktanSecmeliSoru(CoktanSecmeliSoru instance);
    partial void DeleteCoktanSecmeliSoru(CoktanSecmeliSoru instance);
    partial void InsertDogruYanlısSoru(DogruYanlısSoru instance);
    partial void UpdateDogruYanlısSoru(DogruYanlısSoru instance);
    partial void DeleteDogruYanlısSoru(DogruYanlısSoru instance);
    #endregion
		
		public SoruBankasıDataContext() : 
				base(global::Quiz2.Properties.Settings.Default.SoruBankasıConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SoruBankasıDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoruBankasıDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoruBankasıDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SoruBankasıDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kategori> Kategoris
		{
			get
			{
				return this.GetTable<Kategori>();
			}
		}
		
		public System.Data.Linq.Table<Seviye> Seviyes
		{
			get
			{
				return this.GetTable<Seviye>();
			}
		}
		
		public System.Data.Linq.Table<KlasikSoru> KlasikSorus
		{
			get
			{
				return this.GetTable<KlasikSoru>();
			}
		}
		
		public System.Data.Linq.Table<CoktanSecmeliSoru> CoktanSecmeliSorus
		{
			get
			{
				return this.GetTable<CoktanSecmeliSoru>();
			}
		}
		
		public System.Data.Linq.Table<DogruYanlısSoru> DogruYanlısSorus
		{
			get
			{
				return this.GetTable<DogruYanlısSoru>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategori")]
	public partial class Kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ad;
		
		private EntitySet<KlasikSoru> _KlasikSorus;
		
		private EntitySet<CoktanSecmeliSoru> _CoktanSecmeliSorus;
		
		private EntitySet<DogruYanlısSoru> _DogruYanlısSorus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    #endregion
		
		public Kategori()
		{
			this._KlasikSorus = new EntitySet<KlasikSoru>(new Action<KlasikSoru>(this.attach_KlasikSorus), new Action<KlasikSoru>(this.detach_KlasikSorus));
			this._CoktanSecmeliSorus = new EntitySet<CoktanSecmeliSoru>(new Action<CoktanSecmeliSoru>(this.attach_CoktanSecmeliSorus), new Action<CoktanSecmeliSoru>(this.detach_CoktanSecmeliSorus));
			this._DogruYanlısSorus = new EntitySet<DogruYanlısSoru>(new Action<DogruYanlısSoru>(this.attach_DogruYanlısSorus), new Action<DogruYanlısSoru>(this.detach_DogruYanlısSorus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_KlasikSoru", Storage="_KlasikSorus", ThisKey="Id", OtherKey="KategoriId")]
		public EntitySet<KlasikSoru> KlasikSorus
		{
			get
			{
				return this._KlasikSorus;
			}
			set
			{
				this._KlasikSorus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_CoktanSecmeliSoru", Storage="_CoktanSecmeliSorus", ThisKey="Id", OtherKey="KategoriId")]
		public EntitySet<CoktanSecmeliSoru> CoktanSecmeliSorus
		{
			get
			{
				return this._CoktanSecmeliSorus;
			}
			set
			{
				this._CoktanSecmeliSorus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_DogruYanlısSoru", Storage="_DogruYanlısSorus", ThisKey="Id", OtherKey="KategoriId")]
		public EntitySet<DogruYanlısSoru> DogruYanlısSorus
		{
			get
			{
				return this._DogruYanlısSorus;
			}
			set
			{
				this._DogruYanlısSorus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KlasikSorus(KlasikSoru entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_KlasikSorus(KlasikSoru entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
		
		private void attach_CoktanSecmeliSorus(CoktanSecmeliSoru entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_CoktanSecmeliSorus(CoktanSecmeliSoru entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
		
		private void attach_DogruYanlısSorus(DogruYanlısSoru entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_DogruYanlısSorus(DogruYanlısSoru entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seviye")]
	public partial class Seviye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ZorlukDerecesi;
		
		private EntitySet<KlasikSoru> _KlasikSorus;
		
		private EntitySet<CoktanSecmeliSoru> _CoktanSecmeliSorus;
		
		private EntitySet<DogruYanlısSoru> _DogruYanlısSorus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnZorlukDerecesiChanging(string value);
    partial void OnZorlukDerecesiChanged();
    #endregion
		
		public Seviye()
		{
			this._KlasikSorus = new EntitySet<KlasikSoru>(new Action<KlasikSoru>(this.attach_KlasikSorus), new Action<KlasikSoru>(this.detach_KlasikSorus));
			this._CoktanSecmeliSorus = new EntitySet<CoktanSecmeliSoru>(new Action<CoktanSecmeliSoru>(this.attach_CoktanSecmeliSorus), new Action<CoktanSecmeliSoru>(this.detach_CoktanSecmeliSorus));
			this._DogruYanlısSorus = new EntitySet<DogruYanlısSoru>(new Action<DogruYanlısSoru>(this.attach_DogruYanlısSorus), new Action<DogruYanlısSoru>(this.detach_DogruYanlısSorus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZorlukDerecesi", DbType="NVarChar(50)")]
		public string ZorlukDerecesi
		{
			get
			{
				return this._ZorlukDerecesi;
			}
			set
			{
				if ((this._ZorlukDerecesi != value))
				{
					this.OnZorlukDerecesiChanging(value);
					this.SendPropertyChanging();
					this._ZorlukDerecesi = value;
					this.SendPropertyChanged("ZorlukDerecesi");
					this.OnZorlukDerecesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seviye_KlasikSoru", Storage="_KlasikSorus", ThisKey="Id", OtherKey="SeviyeId")]
		public EntitySet<KlasikSoru> KlasikSorus
		{
			get
			{
				return this._KlasikSorus;
			}
			set
			{
				this._KlasikSorus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seviye_CoktanSecmeliSoru", Storage="_CoktanSecmeliSorus", ThisKey="Id", OtherKey="SeviyeId")]
		public EntitySet<CoktanSecmeliSoru> CoktanSecmeliSorus
		{
			get
			{
				return this._CoktanSecmeliSorus;
			}
			set
			{
				this._CoktanSecmeliSorus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seviye_DogruYanlısSoru", Storage="_DogruYanlısSorus", ThisKey="Id", OtherKey="SeviyeId")]
		public EntitySet<DogruYanlısSoru> DogruYanlısSorus
		{
			get
			{
				return this._DogruYanlısSorus;
			}
			set
			{
				this._DogruYanlısSorus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KlasikSorus(KlasikSoru entity)
		{
			this.SendPropertyChanging();
			entity.Seviye = this;
		}
		
		private void detach_KlasikSorus(KlasikSoru entity)
		{
			this.SendPropertyChanging();
			entity.Seviye = null;
		}
		
		private void attach_CoktanSecmeliSorus(CoktanSecmeliSoru entity)
		{
			this.SendPropertyChanging();
			entity.Seviye = this;
		}
		
		private void detach_CoktanSecmeliSorus(CoktanSecmeliSoru entity)
		{
			this.SendPropertyChanging();
			entity.Seviye = null;
		}
		
		private void attach_DogruYanlısSorus(DogruYanlısSoru entity)
		{
			this.SendPropertyChanging();
			entity.Seviye = this;
		}
		
		private void detach_DogruYanlısSorus(DogruYanlısSoru entity)
		{
			this.SendPropertyChanging();
			entity.Seviye = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KlasikSoru")]
	public partial class KlasikSoru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _KategoriId;
		
		private System.Nullable<int> _SeviyeId;
		
		private string _SoruMetni;
		
		private string _CevapMetni;
		
		private string _Doğrucevap;
		
		private System.Nullable<int> _Puan;
		
		private EntityRef<Kategori> _Kategori;
		
		private EntityRef<Seviye> _Seviye;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKategoriIdChanging(System.Nullable<int> value);
    partial void OnKategoriIdChanged();
    partial void OnSeviyeIdChanging(System.Nullable<int> value);
    partial void OnSeviyeIdChanged();
    partial void OnSoruMetniChanging(string value);
    partial void OnSoruMetniChanged();
    partial void OnCevapMetniChanging(string value);
    partial void OnCevapMetniChanged();
    partial void OnDoğrucevapChanging(string value);
    partial void OnDoğrucevapChanged();
    partial void OnPuanChanging(System.Nullable<int> value);
    partial void OnPuanChanged();
    #endregion
		
		public KlasikSoru()
		{
			this._Kategori = default(EntityRef<Kategori>);
			this._Seviye = default(EntityRef<Seviye>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", DbType="Int")]
		public System.Nullable<int> KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeviyeId", DbType="Int")]
		public System.Nullable<int> SeviyeId
		{
			get
			{
				return this._SeviyeId;
			}
			set
			{
				if ((this._SeviyeId != value))
				{
					if (this._Seviye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeviyeIdChanging(value);
					this.SendPropertyChanging();
					this._SeviyeId = value;
					this.SendPropertyChanged("SeviyeId");
					this.OnSeviyeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoruMetni", DbType="NVarChar(250)")]
		public string SoruMetni
		{
			get
			{
				return this._SoruMetni;
			}
			set
			{
				if ((this._SoruMetni != value))
				{
					this.OnSoruMetniChanging(value);
					this.SendPropertyChanging();
					this._SoruMetni = value;
					this.SendPropertyChanged("SoruMetni");
					this.OnSoruMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CevapMetni", DbType="NVarChar(250)")]
		public string CevapMetni
		{
			get
			{
				return this._CevapMetni;
			}
			set
			{
				if ((this._CevapMetni != value))
				{
					this.OnCevapMetniChanging(value);
					this.SendPropertyChanging();
					this._CevapMetni = value;
					this.SendPropertyChanged("CevapMetni");
					this.OnCevapMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doğrucevap", DbType="NChar(250)")]
		public string Doğrucevap
		{
			get
			{
				return this._Doğrucevap;
			}
			set
			{
				if ((this._Doğrucevap != value))
				{
					this.OnDoğrucevapChanging(value);
					this.SendPropertyChanging();
					this._Doğrucevap = value;
					this.SendPropertyChanged("Doğrucevap");
					this.OnDoğrucevapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Int")]
		public System.Nullable<int> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this.OnPuanChanging(value);
					this.SendPropertyChanging();
					this._Puan = value;
					this.SendPropertyChanged("Puan");
					this.OnPuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_KlasikSoru", Storage="_Kategori", ThisKey="KategoriId", OtherKey="Id", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.KlasikSorus.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.KlasikSorus.Add(this);
						this._KategoriId = value.Id;
					}
					else
					{
						this._KategoriId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seviye_KlasikSoru", Storage="_Seviye", ThisKey="SeviyeId", OtherKey="Id", IsForeignKey=true)]
		public Seviye Seviye
		{
			get
			{
				return this._Seviye.Entity;
			}
			set
			{
				Seviye previousValue = this._Seviye.Entity;
				if (((previousValue != value) 
							|| (this._Seviye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seviye.Entity = null;
						previousValue.KlasikSorus.Remove(this);
					}
					this._Seviye.Entity = value;
					if ((value != null))
					{
						value.KlasikSorus.Add(this);
						this._SeviyeId = value.Id;
					}
					else
					{
						this._SeviyeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Seviye");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CoktanSecmeliSoru")]
	public partial class CoktanSecmeliSoru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _KategoriId;
		
		private System.Nullable<int> _SeviyeId;
		
		private string _SoruMetni;
		
		private string _A;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private string _DogruCevap;
		
		private System.Nullable<int> _Puan;
		
		private EntityRef<Kategori> _Kategori;
		
		private EntityRef<Seviye> _Seviye;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKategoriIdChanging(System.Nullable<int> value);
    partial void OnKategoriIdChanged();
    partial void OnSeviyeIdChanging(System.Nullable<int> value);
    partial void OnSeviyeIdChanged();
    partial void OnSoruMetniChanging(string value);
    partial void OnSoruMetniChanged();
    partial void OnAChanging(string value);
    partial void OnAChanged();
    partial void OnBChanging(string value);
    partial void OnBChanged();
    partial void OnCChanging(string value);
    partial void OnCChanged();
    partial void OnDChanging(string value);
    partial void OnDChanged();
    partial void OnDogruCevapChanging(string value);
    partial void OnDogruCevapChanged();
    partial void OnPuanChanging(System.Nullable<int> value);
    partial void OnPuanChanged();
    #endregion
		
		public CoktanSecmeliSoru()
		{
			this._Kategori = default(EntityRef<Kategori>);
			this._Seviye = default(EntityRef<Seviye>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", DbType="Int")]
		public System.Nullable<int> KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeviyeId", DbType="Int")]
		public System.Nullable<int> SeviyeId
		{
			get
			{
				return this._SeviyeId;
			}
			set
			{
				if ((this._SeviyeId != value))
				{
					if (this._Seviye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeviyeIdChanging(value);
					this.SendPropertyChanging();
					this._SeviyeId = value;
					this.SendPropertyChanged("SeviyeId");
					this.OnSeviyeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoruMetni", DbType="NVarChar(250)")]
		public string SoruMetni
		{
			get
			{
				return this._SoruMetni;
			}
			set
			{
				if ((this._SoruMetni != value))
				{
					this.OnSoruMetniChanging(value);
					this.SendPropertyChanging();
					this._SoruMetni = value;
					this.SendPropertyChanged("SoruMetni");
					this.OnSoruMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="NVarChar(250)")]
		public string A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(250)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this.OnBChanging(value);
					this.SendPropertyChanging();
					this._B = value;
					this.SendPropertyChanged("B");
					this.OnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(250)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this.OnCChanging(value);
					this.SendPropertyChanging();
					this._C = value;
					this.SendPropertyChanged("C");
					this.OnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(250)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogruCevap", DbType="NVarChar(250)")]
		public string DogruCevap
		{
			get
			{
				return this._DogruCevap;
			}
			set
			{
				if ((this._DogruCevap != value))
				{
					this.OnDogruCevapChanging(value);
					this.SendPropertyChanging();
					this._DogruCevap = value;
					this.SendPropertyChanged("DogruCevap");
					this.OnDogruCevapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Int")]
		public System.Nullable<int> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this.OnPuanChanging(value);
					this.SendPropertyChanging();
					this._Puan = value;
					this.SendPropertyChanged("Puan");
					this.OnPuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_CoktanSecmeliSoru", Storage="_Kategori", ThisKey="KategoriId", OtherKey="Id", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.CoktanSecmeliSorus.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.CoktanSecmeliSorus.Add(this);
						this._KategoriId = value.Id;
					}
					else
					{
						this._KategoriId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seviye_CoktanSecmeliSoru", Storage="_Seviye", ThisKey="SeviyeId", OtherKey="Id", IsForeignKey=true)]
		public Seviye Seviye
		{
			get
			{
				return this._Seviye.Entity;
			}
			set
			{
				Seviye previousValue = this._Seviye.Entity;
				if (((previousValue != value) 
							|| (this._Seviye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seviye.Entity = null;
						previousValue.CoktanSecmeliSorus.Remove(this);
					}
					this._Seviye.Entity = value;
					if ((value != null))
					{
						value.CoktanSecmeliSorus.Add(this);
						this._SeviyeId = value.Id;
					}
					else
					{
						this._SeviyeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Seviye");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DogruYanlısSoru")]
	public partial class DogruYanlısSoru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _KategoriId;
		
		private System.Nullable<int> _SeviyeId;
		
		private string _SoruMetni;
		
		private string _Dogru;
		
		private string _Yanlıs;
		
		private string _DogruCevap;
		
		private System.Nullable<int> _Puan;
		
		private EntityRef<Kategori> _Kategori;
		
		private EntityRef<Seviye> _Seviye;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKategoriIdChanging(System.Nullable<int> value);
    partial void OnKategoriIdChanged();
    partial void OnSeviyeIdChanging(System.Nullable<int> value);
    partial void OnSeviyeIdChanged();
    partial void OnSoruMetniChanging(string value);
    partial void OnSoruMetniChanged();
    partial void OnDogruChanging(string value);
    partial void OnDogruChanged();
    partial void OnYanlısChanging(string value);
    partial void OnYanlısChanged();
    partial void OnDogruCevapChanging(string value);
    partial void OnDogruCevapChanged();
    partial void OnPuanChanging(System.Nullable<int> value);
    partial void OnPuanChanged();
    #endregion
		
		public DogruYanlısSoru()
		{
			this._Kategori = default(EntityRef<Kategori>);
			this._Seviye = default(EntityRef<Seviye>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", DbType="Int")]
		public System.Nullable<int> KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeviyeId", DbType="Int")]
		public System.Nullable<int> SeviyeId
		{
			get
			{
				return this._SeviyeId;
			}
			set
			{
				if ((this._SeviyeId != value))
				{
					if (this._Seviye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeviyeIdChanging(value);
					this.SendPropertyChanging();
					this._SeviyeId = value;
					this.SendPropertyChanged("SeviyeId");
					this.OnSeviyeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoruMetni", DbType="NVarChar(250)")]
		public string SoruMetni
		{
			get
			{
				return this._SoruMetni;
			}
			set
			{
				if ((this._SoruMetni != value))
				{
					this.OnSoruMetniChanging(value);
					this.SendPropertyChanging();
					this._SoruMetni = value;
					this.SendPropertyChanged("SoruMetni");
					this.OnSoruMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dogru", DbType="NVarChar(250)")]
		public string Dogru
		{
			get
			{
				return this._Dogru;
			}
			set
			{
				if ((this._Dogru != value))
				{
					this.OnDogruChanging(value);
					this.SendPropertyChanging();
					this._Dogru = value;
					this.SendPropertyChanged("Dogru");
					this.OnDogruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yanlıs", DbType="NVarChar(250)")]
		public string Yanlıs
		{
			get
			{
				return this._Yanlıs;
			}
			set
			{
				if ((this._Yanlıs != value))
				{
					this.OnYanlısChanging(value);
					this.SendPropertyChanging();
					this._Yanlıs = value;
					this.SendPropertyChanged("Yanlıs");
					this.OnYanlısChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogruCevap", DbType="NVarChar(250)")]
		public string DogruCevap
		{
			get
			{
				return this._DogruCevap;
			}
			set
			{
				if ((this._DogruCevap != value))
				{
					this.OnDogruCevapChanging(value);
					this.SendPropertyChanging();
					this._DogruCevap = value;
					this.SendPropertyChanged("DogruCevap");
					this.OnDogruCevapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Int")]
		public System.Nullable<int> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this.OnPuanChanging(value);
					this.SendPropertyChanging();
					this._Puan = value;
					this.SendPropertyChanged("Puan");
					this.OnPuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_DogruYanlısSoru", Storage="_Kategori", ThisKey="KategoriId", OtherKey="Id", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.DogruYanlısSorus.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.DogruYanlısSorus.Add(this);
						this._KategoriId = value.Id;
					}
					else
					{
						this._KategoriId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Seviye_DogruYanlısSoru", Storage="_Seviye", ThisKey="SeviyeId", OtherKey="Id", IsForeignKey=true)]
		public Seviye Seviye
		{
			get
			{
				return this._Seviye.Entity;
			}
			set
			{
				Seviye previousValue = this._Seviye.Entity;
				if (((previousValue != value) 
							|| (this._Seviye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Seviye.Entity = null;
						previousValue.DogruYanlısSorus.Remove(this);
					}
					this._Seviye.Entity = value;
					if ((value != null))
					{
						value.DogruYanlısSorus.Add(this);
						this._SeviyeId = value.Id;
					}
					else
					{
						this._SeviyeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Seviye");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
